config/routes.rb
Rails.application.routes.draw do
  get 'home/landing'
  get 'home/index'
  post "home/landing"

  root 'home#landing'
  resources :contacts
  resources :homesg

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        # send email
        ApplicationMailer.signup_confirmation(@contact).deliver
        format.html { redirect_to @contact, notice: 'Obrigado! Logo recebera um email de confirmação' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :phone, :city)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

    # GET /contacts
    # GET /contacts.json
    def index
      @contacts = Contact.all
    end

    # GET /contacts/1
    # GET /contacts/1.json
    def show
    end

    # GET /contacts/new
    def new
      @contact = Contact.new
    end

    # GET /contacts/1/edit
    def edit
    end

    # POST /contacts
    # POST /contacts.json
    def create
      @contact = Contact.new(contact_params)

      respond_to do |format|
        if @contact.save
          # send email
          ApplicationMailer.signup_confirmation(@contact).deliver
          format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
          format.json { render :show, status: :created, location: @contact }
        else
          format.html { render :new }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /contacts/1
    # PATCH/PUT /contacts/1.json
    def update
      respond_to do |format|
        if @contact.update(contact_params)
          format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
          format.json { render :show, status: :ok, location: @contact }
        else
          format.html { render :edit }
          format.json { render json: @contact.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /contacts/1
    # DELETE /contacts/1.json
    def destroy
      @contact.destroy
      respond_to do |format|
        format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_contact
        @contact = Contact.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def contact_params
        params.require(:contact).permit(:name, :email, :phone, :city)
      end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :contact_phone %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :contact_city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<%= render 'home/navbar' %>
<div class="row ri">
  <div class="col l8 offset-l2 s12">
<p id="notice"><%= notice %></p>

<h1>Contatos</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Phone</th>
      <th>City</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.city %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>


<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<%= render 'home/navbar' %>
<div class="row ri">
  <div class="col l4 offset-l4 s12">
    <h1 class="center">Increva-se</h1>
<%= render 'form', contact: @contact %>
</div>
</div>

app/views/contacts/show.html.erb
<%= render 'home/navbar' %>
<div class="row ri">
  <div class="col col l5 offset-l4 s12">
    <p class="cebter" id="notice"><%= notice %></p>
    <div class="card blue-grey darken-1 ">
      <div class="card-content white-text ">
        <span class="card-title">Contatos</span>

        <p>
          <strong>Name:</strong>
          <%= @contact.name %>
        </p>

        <p>
          <strong>Email:</strong>
          <%= @contact.email %>
        </p>

        <p>
          <strong>Phone:</strong>
          <%= @contact.phone %>
        </p>

        <p>
          <strong>City:</strong>
          <%= @contact.city %>
        </p>

      </div>
      <div class="card-action center">
        <h4 class="center white-text">Visite Nossa Pagina Inicial</h4>
      </div>
    </div>
  </div>
</div>

app/views/home/_footer.html.erb
<footer class="page-footer grey">
  <div class="row ">
    <div class="col s12">
      <div class="col s5 center ">
        <h5 class= "center black-text container">Equipe</h5>
        <ul class="collapsible black-text" data-collapsible="accordion">
     <li class="center">
       <div class="collapsible-header black-text center">Sistemas fe Informações FAP-CE</div>
       <div class="collapsible-body white"><span>Cícero Akiles Paulino Olinda<br>Ramon Felizardo da Costa
                                                <br>Ismael Barbosa Ferreira</span></div>
     </li>
       </ul>
      </div>

	</div>
</div>
    </div>
  </div>

<div class="footer-copyright">
<div class="container center">
© 2017 Todos Direitos Reservados.
</div>
</div>
</footer>

app/views/home/_form1.html.erb
<%= form_with(model: contact, local: true) do |form| %>


  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone, id: :contact_phone %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :contact_city %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/home/_missao.html.erb
    <div class="center">
    <div class="col s10 m8">
      <div class="card-panel orange ">
        <h3 class="white-text center">Missão</h3>
        <h5 class="white-text center">Proporcionar serviços de divulgação com eficiência e qualidade no meio informacional, disponibilizando uma interface amigável e intuitiva.<h5>
      </div>
    </div>
  </div>

app/views/home/_navbar.html.erb
<nav class="orange darken-3 lighten-1" role="navigation">
  <div class="nav-wrapper container ">
    <li class="brand-logo" >Sua Loja</li>
    <ul class="right hide-on-med-and-down center ">
      <li><%= link_to 'Sua Loja', home_index_path %></li>
      <li><%= link_to 'Page', home_landing_path %></li>
    </ul>
    <a href="#" data-activates="nav-mobile" class="button-collapse"><i class="material-icons">menu</i></a>
  </div>
</nav>

app/views/home/_valores.html.erb
<div class="center">
<div class="col s10 m8">
  <div class="card-panel orange ">
    <h3 class="white-text center">Missão</h3>
    <h5 class="white-text"><i class="material-icons">check_circle</i>Ética</h5></li>
    <h5 class="white-text"><i class="material-icons">check_circle</i>Qualidade</h5></li>
    <h5 class="white-text"><i class="material-icons">check_circle</i>Responsabilidade com o cliente</h5>
  </div>
</div>
</div>

app/views/home/_visao.html.erb
<div class="center">
<div class="col s10 m8">
  <div class="card-panel orange ">
    <h3 class="white-text center">Visão</h3>
    <h5 class="white-text center">Ser um dos líderes de mercado do segmento de lojas virtuais e propagandas, investindo em tecnologia e inovação.<h5>
  </div>
</div>
</div>

app/views/home/index.html.erb
<%= render 'home/navbar' %>

  <div class="section no-pad-bot  " id="index-banner">
    <div class=" container ">
      <br>
        <div class="col s2 center">
          <img src="/assets/sua.png" width="170" > <!-- notice the "circle" class -->
        </div>
      <div class="row center">
        <h4 class="header col s12 light orange-text">Seu Shopping Virtual!</h4>
        <h4 class="flow-text col s12 blue-text">Onde você poderá oferecer produtos e serviços dentro do nosso site. Você cliente ainda conta com o bônus de anuncio dentro do nosso site.</h4>
      </div>
    </div>
  </div>
  <div class="container">
    <div class="section">
      <!--   Icon Section   -->
      <div class="row">
        <div class="col s12 m4">
          <div class="icon-block">
            <div class="center">
            <h5 class="light-blue darken-4 white-text"><i class="large material-icons ">gps_fixed</i></h5>
              <a class="btn modal-trigger orange darken-6" href="#modal1">Missão</a>
            </div>


          </div>
        </div>
        <div class="col s12 m4">
          <div class="icon-block">
              <div class="center">
            <h5 class="light-blue darken-4 white-text"><i class="large material-icons">visibility</i></h5>
              <a class="btn modal-trigger orange darken-6" href="#modal2">Visão</a>
                </div>
          </div>
        </div>
        <div class="col s12 m4">
          <div class="icon-block">
              <div class="center">
                <h5 class="light-blue darken-4 white-text"><i class="large material-icons">settings</i></h5>
                <a class="btn modal-trigger orange darken-6" href="#modal3">Valores</a>

            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
<%= render 'home/footer' %>

<!-- Modal Structure -->
<div id="modal1" class="modal modal-content">
<div class="modal-content">
<%= render 'home/missao' %>
</div>
</div>

<!-- Modal Structure -->
<div id="modal2" class="modal modal-content">
<div class="modal-content">
<%= render 'home/visao' %>
</div>
</div>

<!-- Modal Structure -->
<div id="modal3" class="modal modal-content">
<div class="modal-content">
<%= render 'home/valores' %>
</div>
</div>

app/views/home/landing.html.erb
<%= render 'home/navbar' %>
    <div class="parallax-container ">
          <div class="parallax"><img src="/assets/estudandes1.jpg"></div>
    </div>
        <!-- 1º quadro -->
    <div class="  section light-blue darken-3">
      <div class="row container">
          <h1 class="header  orange-text center">Está chegando ao Cariri</h1>
          <h3 class="header  white-text center">REPÚBLICA ESTUDANTIL CARIRI</h3>
          <h5 class="white-text text-darken-3 lighten-3 center ">Oferecemos apartamentos de excelente qualidade, wifi, água, energia, chuveiro elétrico, lavanderia, sala de estudo, localização privilegiada, área de lazer com piscina e quadra de esportes, descontos em parceiros da empresa.</h5>
      </div>

    </div>
        <!-- 1º divisão -->
    <div class="section  black ">

    </div>

        <!-- 2º quadro -->
    <div class=" section orange darken-4">
      <div class="row container">

            <h5 class="grey-text white-text lighten-3 center">A República Estudantil Cariri irá hospedar com o máximo de conforto, estudantes de ambos sexos que virão para região do Cariri. Nosso maior orgulho será oferecer a jovens que moram longe de onde estudam a oportunidade de morarem perto de suas respectivas instituições de ensino.</h5>


      </div>
    </div>
        <!-- 2º divisão -->
    <div class="section  black lighten-4 ">

    </div>
        <!-- 3º quadro -->

    <div class=" section yellow accent-2 accent-2">
      <div class="row container cenetr">
          <h2 class="header center black-text">Inscreva-se</h2>
          <h2  class="black-text text-darken-3 lighten-3 center">E receba mais novidades.</h2>
          <div class="center">
            <a class="waves-white btn modal-trigger grey darken-4" href="#modal1">Inscreva-se</a>
          </div>
      </div>
    </div>
        <!-- 2º imagem -->
    <div class="parallax-container">
      <div class="parallax"><img src="/assets/estudantes.jpg"></div>
    </div>


      <!-- Modal Structure -->
    <div id="modal1" class="modal bottom-sheet">
     <div class="modal-content">
      <%= render 'form', contact: @contact %>
     </div>
    </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SuaLoja</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>